### PR TITLE
RISC-V support

### PR DESCRIPTION
**Pull request by tnayuki**
# Description

# Review

- [ ] Add a short description of the change to the CHANGELOG.md file

### CODE REVIEW

**Comment by toru-unity** [comment]
@Amanieu 
Thank you for pointing this out!
The program I ran didn't seem to use libcalls, so I didn't notice my mistake.

**Comment by tnayuki** [comment]
@Amanieu
Thank you for pointing this out!
The program I ran didn't seem to use libcalls, so I didn't notice my mistake.

**Comment by syrusakbary** [comment]
@tnayuki can we open the same PR on wasmer so we can start reviewing it?

**Comment by tnayuki** [comment]
@syrusakbary 

sure, I did it.
https://github.com/wasmerio/wasmer/pull/2800

**Pull request closed without merging**
